ros_ip: 127.0.0.1
ros_master_uri: http://127.0.0.1:11311

max_duration: 300 # Duraci칩n m치xima de la simulaci칩n [s]
sample_time: 0.1 # Tiempo de muestreo [s]
lidar_offset: [0.07, 0] # Posici칩n del sensor en el robot
radius: 0.175 # Radio del robot [m]

tasks:
  - explore